coast:
  source_name: coastline
  geometry_type: polygon

citylike_nonparking_area:
  source_name: osm
  geometry_type: polygon
  query: (SELECT *
         FROM osm_polygon
         WHERE building IS NULL
           AND (amenity IN ('school', 'college', 'university', 'library', 'hospital', 'police', 'fire_station')
             OR landuse IN ('industrial', 'commercial')
             OR aeroway IN ('apron'))
         ORDER BY z_order ASC, way_area DESC) AS citylike

parklike_area:
  source_name: osm
  geometry_type: polygon
  query: (SELECT *,
           (CASE WHEN round(way_area * 1000000) >= 20 THEN 'large' WHEN round(way_area * 1000000) >= 1 THEN 'medium' ELSE 'small' END) AS size
         FROM osm_polygon
         WHERE building IS NULL
           AND (amenity IN ('park')
             OR landuse IN ('recreation_ground', 'greenfield', 'cemetery')
             OR leisure IN ('park', 'pitch', 'track', 'golf_course', 'common', 'playground', 'garden', 'plaza'))
         ORDER BY z_order ASC, way_area DESC) AS parklike

citylike_parking_area:
  source_name: osm
  geometry_type: polygon
  query: (SELECT *
         FROM osm_polygon
         WHERE building IS NULL
           AND amenity = 'parking'
         ORDER BY z_order ASC, way_area DESC) AS citylike

water_area:
  source_name: osm
  geometry_type: polygon
  query: (SELECT *
         FROM osm_polygon
         WHERE landuse IN ('reservoir', 'water')
            OR "natural" IN ('lake', 'water', 'land')
            OR waterway IN ('canal', 'riverbank', 'river')
         ORDER BY z_order ASC) AS water

water_line:
  source_name: osm
  geometry_type: line 
  query: (SELECT * FROM osm_line WHERE waterway IN ('river', 'stream', 'canal') ORDER BY z_order ASC) AS rivers

building_area:
  source_name: osm
  geometry_type: polygon
  query: (SELECT * FROM osm_polygon WHERE building IS NOT NULL ORDER BY z_order ASC, way_area DESC) AS citylike

