coast:
  title: Base Layer
  layer_class: coast

area_water:
  title: Area Water 
  layer_class: water_area

line_water:
  title: Line Water
  layer_class: water_line

municipal_buildings:
  title: Municipal Buildings
  layer_class: citylike_nonparking_area

parks:
  title: Parks
  layer_class: parklike_area

buildings:
  title: Buildings
  layer_class: building_area

